adding Sofy integration demo project
codemagic-ci-cd/codemagic-sample-projects pull request #103
Opened 2022-07-07 13:41 UTC by icarusdust

2022-07-28 06:18 UTC, nevercode-kevin requested changes

2022-07-28 06:18 UTC, nevercode-kevin commented on integrations/sofy_integration_demo_project/codemagic.yaml
> +          cd . && flutter build apk --release --build-name=1.0.0 --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
```suggestion
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true          
      - name: Build APK with Flutter  
        script: |
          flutter build apk --release --build-name=1.0.0 --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
```

2022-07-28 06:18 UTC, nevercode-kevin commented on integrations/sofy_integration_demo_project/codemagic.yaml
> +        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
```suggestion
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
```

2022-07-28 06:18 UTC, nevercode-kevin commented on integrations/sofy_integration_demo_project/codemagic.yaml
> +          # keyAlias=$FCI_KEY_ALIAS
```suggestion
          # storePassword=$CM_KEYSTORE_PASSWORD
          # keyPassword=$CM_KEY_PASSWORD
          # keyAlias=$CM_KEY_ALIAS
```

2022-07-28 06:18 UTC, nevercode-kevin commented on integrations/sofy_integration_demo_project/codemagic.yaml
> +        ignore_failure: true
```suggestion
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true          
```

2022-07-28 06:18 UTC, nevercode-kevin commented on integrations/sofy_integration_demo_project/codemagic.yaml
> +        channel: '#builds'
```suggestion
        channel: "#builds"
```

2022-07-28 07:31 UTC, icarusdust commented
Done!

2022-07-28 07:57 UTC, nevercode-kevin requested changes

2022-07-28 07:57 UTC, nevercode-kevin commented on integrations/sofy_integration_demo_project/codemagic.yaml
> +          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
```suggestion
          echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
```

2022-07-28 07:57 UTC, nevercode-kevin commented on integrations/sofy_integration_demo_project/codemagic.yaml
> +          # storeFile=/tmp/keystore.keystore
```suggestion
          # storeFile=$CM_KEYSTORE_PATH
```

2022-07-28 07:57 UTC, nevercode-kevin commented on integrations/sofy_integration_demo_project/codemagic.yaml
> +      - name: Schedule an automation test with Sofy
The name of this script step is the same as the previous one. I see that it uses a different endpoint, so rename the s cript to show that something different is being done.

2022-07-29 09:15 UTC, icarusdust commented
Changes made

2022-07-29 09:21 UTC, nevercode-kevin approved these changes
LGTM

2022-07-29 09:22 UTC, merged