Perfecto sample project
codemagic-ci-cd/codemagic-sample-projects pull request #114
Opened 2022-08-01 14:18 UTC by icarusdust

2022-08-07 08:24 UTC, nevercode-kevin requested changes

2022-08-07 08:24 UTC, nevercode-kevin commented on integrations/perfecto_sample_project/codemagic.yaml
> +      - name: Upload app to Perfect
```suggestion
      - name: Upload app to Perfecto
```

2022-08-08 13:37 UTC, icarusdust commented on integrations/perfecto_sample_project/codemagic.yaml
> +      - name: Upload app to Perfect
done

2022-08-08 13:55 UTC, nevercode-kevin approved these changes
LGTM

2022-08-08 13:55 UTC, merged