Add Emerge integration
codemagic-ci-cd/codemagic-sample-projects pull request #115
Opened 2022-08-13 17:03 UTC by nevercode-rudrank

This PR contains the [Emerge](https://www.emergetools.com/) integration demo project. 

It includes the `Fastfile` that has an example of uploading the archive to Emerge Tools website and a `codemagic.yaml` that consists of the scripts for uploading the iOS build of part of your Codemagic CI/CD workflow.

2022-08-16 13:44 UTC, nevercode-kevin requested changes

2022-08-16 13:44 UTC, nevercode-kevin commented on integrations/emerge-tools-integration-demo-project/codemagic.yaml
> +          # agvtool new-version -all $(($BUILD_NUMBER + 1))
```suggestion
```

2022-08-16 14:50 UTC, nevercode-rudrank commented on integrations/emerge-tools-integration-demo-project/codemagic.yaml
> +          # agvtool new-version -all $(($BUILD_NUMBER + 1))
OUCH

2022-08-24 11:30 UTC, nevercode-kevin approved these changes
LGTM

2022-08-24 11:33 UTC, merged