Add Capawesome Cloud demo project
codemagic-ci-cd/codemagic-sample-projects pull request #192
Opened 2024-05-02 09:27 UTC by robingenz

This PR adds instructions on how to integrate [Capawesome Cloud](https://capawesome.io/cloud/) with Codemagic. 

Related to https://github.com/codemagic-ci-cd/codemagic-docs/pull/2503

2024-11-08 08:54 UTC, icarusdust requested changes
Also, I think it is a good idea to add iOS workflow as well. We have a sample project here: https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/main/ionic/ionic-capacitor-demo-project/codemagic.yaml

2024-11-08 08:54 UTC, icarusdust commented on integrations/capawesome_cloud_demo_project/codemagic.yaml
> +    instance_type: mac_mini_m1
please update mac_mini_m1 to mac_mini_m2

2024-11-09 13:11 UTC, robingenz commented
@icarusdust Done. Let me know if i need to update anything else.

2024-11-14 07:03 UTC, icarusdust approved these changes

2024-11-14 07:03 UTC, merged